#%RAML 0.8

title: Bagagem RAML Contract
baseUri: http://{domain}/bagagem
/a:
  get:
    responses:
      200:
  /b:
    get:
      responses:
        200:
      queryParameters:
        search:
          displayName: Search field
          type: string
          required: true
        order:
          displayName: Order field
          type: number
          required: false
        quantity:
          displayName: Quantity field
          type: integer
          required: false
        start:
          displayName: Start date
          type: date
          required: false
        lazy:
          displayName: Lazy flag
          type: boolean
          required: false
    /c:
      get:
        responses:
          200:
      /d:
        get:
          responses:
            200:
        /e:
          get:
            responses:
              200:
          /{id}:
            get:
              responses:
                200: