#%RAML 0.8

title: Bagagem RAML Contract
baseUri: http://{domain}/bagagem
/a:
  get:
    responses:
      200:
  /b:
    get:
      responses:
        200:
    /c:
      get:
        responses:
          200:
      /d:
        get:
          responses:
            200:
        /e:
          get:
            responses:
              200:
          /{id}:
            get:
              responses:
                200: