#%RAML 0.8

title: Bagagem RAML Contract
baseUri: http://{domain}:8081/bagagem
/login:
  post:
    headers:
      authorization:
        type: string
        required: true
    body:
      application/json:
        schema: |
          {
              "username": {
                "type": "string",
                "required": true
              },
              "password": {
                "type": "string",
                "required": true
              }
          }
        example: |
          {
            "username": "otavio",
            "password": "123456"
          }
    responses:
      200:
      application/json:
        schema: |
          {
              "username": {
                "type": "string",
                "required": true
              },
              "password": {
                "type": "string",
                "required": true
              }
          }
        example: |
          {
            "username": "otavio",
            "password": "123456"
          }
      401: