#%RAML 0.8
title: Security RAML Contract
baseUri: http://{domain}:8081/rest/social
traits:
  - secured:
      headers:
        authorization:
          type: string
          required: true
/contents:
  /{contentType}:
    /{contentId}:
      /ratings:
        is: [secured]
        post:
          body:
            application/json:
              schema: |
                {
                  "type": "object",
                  "required": true,
                  "properties": {
                    "criteriaId": {
                      "type": "string",
                      "required": true
                    },
                    "criteriaTitle": {
                      "type": "string",
                      "required": true
                    },
                    "contentTitle": {
                      "type": "string",
                      "required": true
                    },
                    "rating": {
                      "type": [ "null", "integer" ],
                      "required": true
                    }
                  }
                }
          responses:
            200:
      /likes:
        is: [secured]
        post:
          body:
            application/json:
              schema: |
                {
                  "type": "object",
                  "required": true,
                  "properties": {
                    "contentTitle": {
                      "type": "string",
                      "required": true
                    },
                    "liked": {
                      "type": [ "null", "boolean" ],
                      "required": true
                    }
                  }
                }
          responses:
            200: