#%RAML 0.8
title: Bagagem RAML Contract
baseUri: http://{domain}:8081/rest/lms
schemas:
  - course-list-student-view: !include schema/course-list-student-view.json
    course-student-view: !include schema/course-student-view.json
    practical-activity-student-view: !include schema/practical-activity-student-view.json
traits:
  - secured:
      headers:
        authorization:
          type: string
          required: true
/students:
  /{studentId}:
    /courses:
      is: [secured]
      get:
        responses:
          200:
            body:
              application/json:
                schema: course-list-student-view
      /{courseId}:
        is: [secured]
        get:
          responses:
            200:
              body:
                application/json:
                  schema: course-student-view
    /practical-activity-lessons:
      /{lessonId}:
        is: [secured]
        get:
          responses:
            200:
              body:
                application/json:
                  schema: practical-activity-student-view
/practical-activity-lessons:
  /{lessonId}:
    /comments:
      is: [secured]
      post:
        body:
          application/json:
            schema: |
              {
                "type": "object",
                "required": true,
                "properties": {
                  "personName": {
                    "type": "string",
                    "required": true
                  },
                  "comment": {
                    "type": "object",
                    "required": true,
                    "properties": {
                      "message": {
                        "type": "string",
                        "required": false
                      }
                    }
                  }
                }
              }
        responses:
          200:
/scorm-lesson-enrollments:
  /{lessonId}:
    /start:
      is: [secured]
      post:
        body:
          application/json:
            schema: |
              {
                "type": "object",
                "required": true,
                "properties": {
                  "personName": {
                    "type": "string",
                    "required": true
                  }
                }
              }
        responses:
          200:
            body:
              application/json:
                schema: |
                  {
                    "type": "object",
                    "required": true,
                    "properties": {
                      "url": {
                        "type": "string",
                        "required": true
                      }
                    }
                  }